@echo off
set "SWITCHEROONIE_PACKAGE=%~dp0dist\VRC-SWITCHEROONIE-0.2.4-final"
if not exist "%SWITCHEROONIE_PACKAGE%\VRC-SWITCHEROONIE.exe" set "SWITCHEROONIE_PACKAGE=%~dp0dist\VRC-SWITCHEROONIE-0.2.4"
if not exist "%SWITCHEROONIE_PACKAGE%\VRC-SWITCHEROONIE.exe" set "SWITCHEROONIE_PACKAGE=%~dp0dist\VRC-SWITCHEROONIE-0.2.2-final"
if not exist "%SWITCHEROONIE_PACKAGE%\VRC-SWITCHEROONIE.exe" set "SWITCHEROONIE_PACKAGE=%~dp0dist\VRC-SWITCHEROONIE-0.2.2"
if not exist "%SWITCHEROONIE_PACKAGE%\VRC-SWITCHEROONIE.exe" set "SWITCHEROONIE_PACKAGE=%~dp0dist\VRC-SWITCHEROONIE-0.2.1-final"
if not exist "%SWITCHEROONIE_PACKAGE%\VRC-SWITCHEROONIE.exe" set "SWITCHEROONIE_PACKAGE=%~dp0dist\VRC-SWITCHEROONIE-0.2.1"
if not exist "%SWITCHEROONIE_PACKAGE%\VRC-SWITCHEROONIE.exe" set "SWITCHEROONIE_PACKAGE=%~dp0dist\VRC-SWITCHEROONIE-0.2.0-final"
if not exist "%SWITCHEROONIE_PACKAGE%\VRC-SWITCHEROONIE.exe" (
  echo Build the portable package with tools\Build.ps1 first.
  exit /b 1
)
start "" "%SWITCHEROONIE_PACKAGE%\VRC-SWITCHEROONIE.exe" --launch
