file(READ "${DRIVER_ROOT}/driver.vrdrivermanifest" manifest)
string(JSON driver_name GET "${manifest}" name)
if(NOT driver_name STREQUAL "switcheroonie")
  message(FATAL_ERROR "Packaged manifest does not identify the owned companion driver")
endif()
file(READ "${DRIVER_ROOT}/resources/settings/default.vrsettings" defaults)
string(JSON section_count LENGTH "${defaults}")
string(JSON key_count LENGTH "${defaults}" driver_switcheroonie)
string(JSON priority_type TYPE "${defaults}" driver_switcheroonie loadPriority)
string(JSON priority GET "${defaults}" driver_switcheroonie loadPriority)
if(NOT section_count EQUAL 1 OR NOT key_count EQUAL 1 OR
   NOT priority_type STREQUAL "NUMBER" OR NOT priority EQUAL 20000)
  message(FATAL_ERROR "Packaged settings must set only driver_switcheroonie.loadPriority=20000")
endif()
message(STATUS "Packaged owned-driver priority and resource path verified")
